server:
  port: 9050
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
      
spring:
  application:
    name: UI
  security:
    user:
      password: none
  
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    user:
      path: /user/**
      service-id: UserApp
      
      
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9030/uaa/oauth/token
      user-authorization-uri: http://localhost:9030/uaa/oauth/authorize
      client-id: voyvas
      client-secret: aaa
      scope:
        - webapp
    resource:
      jwt:
        key-value: abc
logging:
  level:
    org.springframework.security: DEBUG